### ISSUE TITLE
What's your python version?

### ISSUE THREAD

**Issue by IcyFeather233** [GAIR-NLP/OPO#7]

**Comment by IcyFeather233** [comment]
My environment:
Macbook Pro M2
conda 23.7.4

When I use `pip install -r requirements.txt`:

If I use python 3.7, it shows:
```
ERROR: Could not find a version that satisfies the requirement faiss-gpu==1.7.2 (from versions: none)
ERROR: No matching distribution found for faiss-gpu==1.7.2
```

If I use python 3.8, it shows:
```
ERROR: Ignored the following versions that require a different python version: 4.31.0 Requires-Python >=3.8.0; 4.32.0 Requires-Python >=3.8.0; 4.32.1 Requires-Python >=3.8.0; 4.33.0 Requires-Python >=3.8.0; 4.33.1 Requires-Python >=3.8.0; 4.33.2 Requires-Python >=3.8.0; 4.33.3 Requires-Python >=3.8.0; 4.34.0 Requires-Python >=3.8.0; 4.34.1 Requires-Python >=3.8.0; 4.35.0 Requires-Python >=3.8.0; 4.35.1 Requires-Python >=3.8.0; 4.35.2 Requires-Python >=3.8.0; 4.36.0 Requires-Python >=3.8.0; 4.36.1 Requires-Python >=3.8.0; 4.36.2 Requires-Python >=3.8.0; 4.37.0 Requires-Python >=3.8.0; 4.37.1 Requires-Python >=3.8.0; 4.37.2 Requires-Python >=3.8.0; 4.38.0 Requires-Python >=3.8.0; 4.38.1 Requires-Python >=3.8.0
ERROR: Could not find a version that satisfies the requirement transformers==4.33.1 (from versions: 0.1, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.6.0, 2.7.0, 2.8.0, 2.9.0, 2.9.1, 2.10.0, 2.11.0, 3.0.0, 3.0.1, 3.0.2, 3.1.0, 3.2.0, 3.3.0, 3.3.1, 3.4.0, 3.5.0, 3.5.1, 4.0.0rc1, 4.0.0, 4.0.1, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.3.0rc1, 4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.4.0, 4.4.1, 4.4.2, 4.5.0, 4.5.1, 4.6.0, 4.6.1, 4.7.0, 4.8.0, 4.8.1, 4.8.2, 4.9.0, 4.9.1, 4.9.2, 4.10.0, 4.10.1, 4.10.2, 4.10.3, 4.11.0, 4.11.1, 4.11.2, 4.11.3, 4.12.0, 4.12.1, 4.12.2, 4.12.3, 4.12.4, 4.12.5, 4.13.0, 4.14.0, 4.14.1, 4.15.0, 4.16.0, 4.16.1, 4.16.2, 4.17.0, 4.18.0, 4.19.0, 4.19.1, 4.19.2, 4.19.3, 4.19.4, 4.20.0, 4.20.1, 4.21.0, 4.21.1, 4.21.2, 4.21.3, 4.22.0, 4.22.1, 4.22.2, 4.23.0, 4.23.1, 4.24.0, 4.25.0, 4.25.1, 4.26.0, 4.26.1, 4.27.0, 4.27.1, 4.27.2, 4.27.3, 4.27.4, 4.28.0, 4.28.1, 4.29.0, 4.29.1, 4.29.2, 4.30.0, 4.30.1, 4.30.2)
ERROR: No matching distribution found for transformers==4.33.1
```

**Comment by cpaaax** [comment]
Thank you for your interest in our work. We have conducted our code testing using Python 3.9. Please note that faiss-gpu is not compatible with OSX (https://github.com/facebookresearch/faiss/blob/be1242775a6e7c025c3ab48388d95bb6a5377d8c/INSTALL.md). As an alternative, you can install faiss-cpu in place of faiss-gpu. 
`pip install faiss-cpu`

**Comment by IcyFeather233** [comment]
Thanks!

**Comment by IcyFeather233** [comment]
> Thank you for your interest in our work. We have conducted our code testing using Python 3.9. Please note that faiss-gpu is not compatible with OSX (https://github.com/facebookresearch/faiss/blob/be1242775a6e7c025c3ab48388d95bb6a5377d8c/INSTALL.md). As an alternative, you can install faiss-cpu in place of faiss-gpu. `pip install faiss-cpu`

It seems that Mac cannot run this project, cause when it comes to the Evaluation Step, it will need faiss-gpu:
```
  File "/Users/xxx/PycharmProjects/OPO/retrieval/retrieval_relevant_docs.py", line 215, in retrieve
    retrieval_texts = self.similarity_search(retrieval_source_text_embed_pairs, ques_text_embed_pairs,
  File "/Users/xxx/PycharmProjects/OPO/retrieval/retrieval_relevant_docs.py", line 139, in similarity_search
    res = faiss.StandardGpuResources()
AttributeError: module 'faiss' has no attribute 'StandardGpuResources'
```

**Comment by IcyFeather233** [comment]
> > Thank you for your interest in our work. We have conducted our code testing using Python 3.9. Please note that faiss-gpu is not compatible with OSX (https://github.com/facebookresearch/faiss/blob/be1242775a6e7c025c3ab48388d95bb6a5377d8c/INSTALL.md). As an alternative, you can install faiss-cpu in place of faiss-gpu. `pip install faiss-cpu`
> 
> It seems that Mac cannot run this project, cause when it comes to the Evaluation Step, it will need faiss-gpu:
> 
> ```
>   File "/Users/xxx/PycharmProjects/OPO/retrieval/retrieval_relevant_docs.py", line 215, in retrieve
>     retrieval_texts = self.similarity_search(retrieval_source_text_embed_pairs, ques_text_embed_pairs,
>   File "/Users/xxx/PycharmProjects/OPO/retrieval/retrieval_relevant_docs.py", line 139, in similarity_search
>     res = faiss.StandardGpuResources()
> AttributeError: module 'faiss' has no attribute 'StandardGpuResources'
> ```

Solved. Commented this logic branch is ok.
