### ISSUE TITLE
May I ask if it is possible to use open-source models and open-source embedding models, such as Chatglm3 and M3e, to complete "Extracting the embeddings of the rule data"？

### ISSUE THREAD

**Issue by lai-serena** [GAIR-NLP/OPO#8]
May I ask if it is possible to use open-source models and open-source embedding models, such as Chatglm3 and M3e, to complete "Extracting the embeddings of the rule data"？

**Comment by dtllm** [comment]
Maybe？If can make better

**Comment by cpaaax** [comment]
Thank you for your interest in our work. Of course, you can extract the embeddings using open-source models. Since we haven't tested embedding models like the M3e, we are unsure about their performance. We encourage you to give it a try.

**Comment by lai-serena** [comment]
ok,thanks

**Comment by TZJ1212** [comment]
可以用来给自己的微调模型测试吗

**Comment by TZJ1212** [comment]
可以用来给自己的微调模型做测试吗
